# Default values for universal-agent-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageOperator:
  registry: docker.io
  registryTokenSecretName:
  registryToken:
  repository: eginnovations/universal-agent-operator
  pullPolicy: IfNotPresent
  tag: "0.0.11"

clusterType:

nodeAffinity:
  key:
  operator:
  values: []

operator:
  annotations: {}
  labels: {}

imagePullSecrets: []

failurePolicy:

injectionSpecificNamespace: []

certManager: false

cert-manager:
  namespace: cert-manager
  installCRDs: true
