# Default values for universal-agent-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imageOperator:
  registry: docker.io
  repository: eginnovations/universal-agent-operator
  pullPolicy: IfNotPresent
  tag: "0.0.8"

imageProxy:
  registry: gcr.io
  repository: kubebuilder/kube-rbac-proxy
  pullPolicy: IfNotPresent
  tag: "v0.13.1"

imagePullSecrets: []

certManager: false

cert-manager:
  namespace: cert-manager
  installCRDs: true
